language: python
os:
  - linux
python:
  - 3.6
install:
  - pip install flake8 arjun
before_script:
  # stop the build if there are Python syntax errors
  - flake8 . --count --select=E901,E999,F401,F701,F702,F706,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - arjun -u https://public-firing-range.appspot.com/reflected/parameter/body -t 2 -oJ result.json
